name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:       
    - name: Setup Node.js
      uses: actions/setup-node@v2
    - name: Instalation quicktype
      run: sudo npm install -g quicktype
    - name: Instalation heroku
      run: npm install -g heroku
    - name: Checkout repository with submodules and generate models
      run: |
        git clone --recurse-submodules https://github.com/CrisBogucki/cb-msc-g-auth.git
        cd cb-msc-g-auth
        export TERM=xterm
        ./update.sh
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        cd cb-msc-g-auth
        dotnet restore
    - name: Build
      run: | 
        cd cb-msc-g-auth
        dotnet build --no-restore
    - name: Test
      run: | 
        cd cb-msc-g-auth
        dotnet test --no-build --verbosity normal
      
      
