name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:     
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Instalation QuickType
      run: |
        npm install -g quicktype
    - name: Checkout repository with submodules and generate models
      run: |
        git clone --recurse-submodules https://github.com/CrisBogucki/cb-msc-g-auth.git
        cd cb-msc-g-auth 
        git submodule update --remote 
        cd lib/smp-lib/ 
        export TERM=xterm
        ./generate.sh -m g-auth -t cs
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
      
