name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:       
    - name: Checkout repository with submodules
      run: git clone --recurse-submodules https://github.com/CrisBogucki/cb-msc-g-auth.git
    - name: ./cb-msc-g-auth git submodule update --remote
      run: ./cb-msc-g-auth git submodule update --remote
    - name: cd lib/smp-lib/
      run: cd lib/smp-lib/
    - name: sudo chmod 777 ./generate.sh
      run: sudo chmod 777 ./generate.sh
    - name: ./generate.sh -m g-auth -t cs
      run: ./generate.sh -m g-auth -t cs
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
      
